# https://github.com/atom/ci/blob/master/README.md

language: generic

node_js:
  - "4"

env:
  global:
    - APM_TEST_PACKAGES="linter"
    - ATOM_LINT_WITH_BUNDLED_NODE="true"

  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

os:
  - osx

script: 'npm run ci'

notifications:
  email:
    on_success: never
    on_failure: change
